### ISSUE TITLE
Problem with applet installation on physical card

### ISSUE THREAD

**Issue by owlet123** [JavaCardSpot-dev/SatoChipApplet#11]
Hi,
I have a problem with applet installation on physical card G+D Smartcafe 6.0 80K.

First, I create CAP file using Gradle wrapper with the command:
`./gradlew buildJavaCard --info` 
And I try to install it on the card with the command:
`gp -emv --install applet.cap -d`
Installation ends with the following exception:
`openkms.gp.GPException: LOAD failed SW: 6A80`

I suppose that CAP file and GP program are correct because I can install applet on JavaCos A40 correctly. But it is not working because this card does not support ECDSA used in the project.

Could you help me to install applet correctly on Smartcafe 6.0 80K?

There is a snapshot with stacktrace:

<img width="946" alt="gp_install" src="https://user-images.githubusercontent.com/17992097/38871961-72cd1b94-4252-11e8-9f35-8655406d50fc.PNG">

**Comment by petrs** [comment]
Hi, 
there are many possible reasons why applet cannot be uploaded, but we can make accurate guess here as we know exactly when the problem occurs and also that it worked on another card. The applet installation consists of two parts: upload (move of *.cap to card) and install (creating new instance from uploaded cap). Only first APDU from upload sequence was transmitted, so card decided to intterupt upload based on information extractable just from the first part of cap file which contains header (see DECAFFED magic word at the start). The header contains info about convertor target version (e.g., 2.2.2 or 3.0.5). Most cards will refuse to load anything converted with newer convertor than the version supported by card (even when no API calls from newer version are actually used in applet). 

Based on https://www.fi.muni.cz/~xsvenda/jcalgtest/table.html, both your cards are supporting JCAPI 3.0.x. So try to convert with convertor version 3.0.1 and see if it will get loaded. If only specific constant from the newer version is required, try to add it manually (e.g., ALG_EC_FP LENGTH_EC_FP_521 was introduced only in 3.0.4 but older cards may support still suppport EC_FP when length of key is directly specified as 521 instead of LENGTH_EC_FP_521 and converted with 3.0.1 convertor)  

Alternatively, the applet may specify too large memory requirements - but that shoudl not be the problem here.

Please try it and post the results

**Comment by owlet123** [comment]
I used JC 3.0.4 so I tried to set lower version JC 3.0.3 and now it works. Applet does not use EC_FP_512, so this wasn't problem.

Thank you, @petrs.
